#!/bin/bash

if [ ! "$1" ]
then
	echo -n "minor version: "
	read minor
else
	minor=$1
fi

topdir=$(pwd)

lastminor=$(($minor-1))

tag=r0_7_$minor
version=0.7.$minor
lasttag=r0_7_$lastminor

export CVSROOT=cvs.comedi.org:/var/cvs

rm -rf comedilib-${version}

echo "deleting tag $tag"
cvs rtag -d $tag comedilib

echo "tagging $tag"
cvs rtag $tag comedilib

echo "exporting"
cvs export -r $tag -d comedilib-${version} comedilib

echo "diffing"
cvs rdiff -u -r $lasttag -r $tag comedilib >patch-comedilib-$version

cd comedilib-$version

echo version=${version} >version
rm etc/rel_comedilib
rm todo
make -C doc

cd ${topdir}

tar -czf comedilib-$version.tgz comedilib-$version

