#!/bin/sh
#
# hotplug script for USBDUX. Mon Oct 20 10:08:09 BST 2003. 
# Bernd.Porr@cn.stir.ac.uk
#
#
#
#look for comedi config
COMEDI_CONFIG=
#
if [ -e /usr/local/sbin/comedi_config ]; then
	COMEDI_CONFIG=/usr/local/sbin/comedi_config
fi
if [ -e /usr/sbin/comedi_config ]; then 
        COMEDI_CONFIG=/usr/sbin/comedi_config
fi
if [ -e /sbin/comedi_config ]; then 
        COMEDI_CONFIG=/sbin/comedi_config
fi
#
#
#look for the firmware
USBDUX_FIRMWARE=
if [ -e /usr/share/usb/usbdux_firmware.hex ]; then 
        USBDUX_FIRMWARE=/usr/share/usb/usbdux_firmware.hex
fi
if [ -e /usr/local/share/usb/usbdux_firmware.hex ]; then
        USBDUX_FIRMWARE=/usr/local/share/usb/usbdux_firmware.hex
fi
#
#
# in 2.6 there might be a race condition between
# the usbdevfs and this hotplug script.
# Therefore we wait a bit to make sure that /proc/bus/usb/... is there.
if ! [ -e $DEVICE ]; then
sleep 1
fi
#
# If the device is still not existing probably the usbdevfs hasn't been
# mounted.
if ! [ -e $DEVICE ]; then
    echo "usbdux hotplug: /proc/bus/usb/... does not exist"
    echo "Please make sure that usbdevfs is mounted."
    exit 1
fi
#
#
# firmware upload into the usb device
fxload -v -2 -I $USBDUX_FIRMWARE
#
#
# If you have more than one device please add/uncomment
# 
# just to make sure we remove the comedi device
$COMEDI_CONFIG -r /dev/comedi0
# $COMEDI_CONFIG -r /dev/comedi1
#
# connecting the comedi device comedi0 with the module usbdux
$COMEDI_CONFIG /dev/comedi0 usbdux
# $COMEDI_CONFIG /dev/comedi1 usbdux
#
#
